version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-latest
    ports:
      - 5434:5432
    env_file:
      - ./.docker/postgres.env
    volumes:
      - ./.docker/data/postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3010:3010'
    volumes:
      - ./:/app
    depends_on:
      - postgres
    env_file:
      - .env
    command: ['pnpm', 'run', 'start']
