version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-latest
    ports:
      - 5432:5432
    env_file:
      - ./.docker/postgres.env
    volumes:
      - ./.docker/data/postgres_data:/var/lib/postgresql/data
